### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by WakingHours-GitHub** [Jung-Jun-Uk/UNPG#7]
cosine_progress = cosine_iter / self.total_cosine_iters
ZeroDivisionError: float division by zero

when i run train.sh script. this error occur. 
ny train.sh as follow:
```
python train.py \
    --model 'iresnet-50' --head 'cosface' \
    --aux 'unpg' --data 'data/webface.yaml' \
    --max_epoch 30 \
    --hyp 'data/hyp.yaml' --name 'example' --device 6,7
```
please any soluation can fix this problem, i try add eps in devision, but something is error, i can't train...

**Comment by junuke** [comment]
I think the problem is that self.total_cosine_iters is 0. 

Can you show me the each args in "scheduler = CosineWarmupLr(optimizer, batches_per_epoch, opt.max_epoch, base_lr=hyp['lr'], warmup_epochs=hyp['warmup_epochs']) " 

each eargs: batches_per_epoch, opt.max_epoch, hyp['lr'], and hyp['warmup_epochs']

please check the batches_per_epoch size
